### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by tvojamajka** [MATF-RG17/RG124-tower-defense#1]
Završena je početna verzija projekta RG124-tower-defense.

**Comment by ivan-cukic-matf** [comment]
Nemam dodatnih zadataka, samo pitanje - da li mislite da je u ovome neka funkcija višak:

`fabs(sqrt(...))`

**Comment by tvojamajka** [comment]
Nije višak, u kodu je napisano 

 `fabs(sqrt(...) - 1)`

a to može biti negativna vrednost.

**Comment by ivan-cukic-matf** [comment]
`sqrt` je višak - ako je `sqrt(x)` u okolini jedinice, onda je i `x` (samo uz malo drugačije EPS)
